name: Otomatik Siralama Guncellemesi

on:
  schedule:
    # Her gece Türkiye saati ile 11:00'da çalışır
    - cron: '13 1 * * *'
  workflow_dispatch: # Test edebilmen için manuel çalıştırma butonu ekler

jobs:
  guncelle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install puppeteer axios
      - env:
          ADMIN_SIFRE: ${{ secrets.ADMIN_SIFRE }}
          API_KEY: ${{ secrets.API_KEY }}
        run: node bot.js
      - run: |
          git config --global user.name 'Siralama Botu'
          git config --global user.email 'bot@otomasyon.com'
          git add sonuc.txt
          git commit -m "Canlı maç sonuçlarıyla otomatik güncelleme" || exit 0
          git push
